name: Norminette

on:
  push:
  pull_request:

jobs:
  norm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette

      - name: Run Norminette
        run: |
            norminette
      - name: Check forbidden functions
        run: |
          if grep -R "exit("; then exit 1; fi
